ALTER TABLE "Order"
ADD COLUMN "quotedDistanceKm" DOUBLE PRECISION,
ADD COLUMN "quotedDurationMinutes" INTEGER,
ADD COLUMN "baseFare" DOUBLE PRECISION,
ADD COLUMN "distanceFare" DOUBLE PRECISION,
ADD COLUMN "serviceFee" DOUBLE PRECISION,
ADD COLUMN "priorityFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "pickupCode" TEXT,
ADD COLUMN "dropoffCode" TEXT,
ADD COLUMN "cancelledAt" TIMESTAMP(3),
ADD COLUMN "driverAcceptedAt" TIMESTAMP(3),
ADD COLUMN "pickedUpAt" TIMESTAMP(3),
ADD COLUMN "deliveredAt" TIMESTAMP(3);
